services:
  bd-service-postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5471:5432"
    restart: always
  api_service:
    build: ./apiService
    env_file:
      - .env
    depends_on:
      - bd-service-postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: