services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5471:5432"
    restart: always

  db_service:
    build:
      context: ./dbService
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "50051:50051"
    restart: on-failure

  api_service:
    build:
      context: ./apiService
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
      - db_service
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data:
